// src/content/config.ts — type-safe collections for Astro
import { defineCollection, z } from "astro:content";

const projects = defineCollection({
  type: "data", // JSON, generated by federate.ts
  schema: z.object({
    slug: z.string(),
    title: z.string(),
    tagline: z.string(),
    status: z.enum(["active", "shipped", "archived"]),
    stack: z.array(z.string()),
    repo: z.string().url(),
    demo: z.string().url().optional(),
    accent: z.tuple([z.number(), z.number(), z.number()]).optional(), // OKLCH [L C H]
    featured: z.boolean().default(false),
    order: z.number().default(0),
  }),
});

const devlogs = defineCollection({
  type: "content", // Markdown, generated by federate.ts
  schema: z.object({
    title: z.string(),
    date: z.coerce.date(),
    project: z.string(),
    tags: z.array(z.string()).default([]),
    draft: z.boolean().default(false),
  }),
});

// native, lives in-repo (not federated)
const cv = defineCollection({
  type: "content",
  schema: z.object({
    section: z.enum(["experience", "education", "skills", "certifications", "awards"]),
    title: z.string(),
    org: z.string().optional(),
    start: z.string().optional(),
    end: z.string().optional(),
    order: z.number().default(0),
  }),
});

const music = defineCollection({
  type: "data",
  schema: z.object({
    title: z.string(),
    source: z.enum(["soundcloud", "bandcamp"]),
    embedId: z.string(),      // just the ID/url fragment — no scraping
    year: z.number().optional(),
    accent: z.tuple([z.number(), z.number(), z.number()]).optional(), // OKLCH [L C H]
  }),
});

export const collections = { projects, devlogs, cv, music };
