// src/content/config.ts — type-safe collections for Astro
import { defineCollection, z } from "astro:content";

const projects = defineCollection({
  type: "data", // JSON, generated by federate.ts
  schema: z.object({
    slug: z.string(),
    title: z.string(),
    tagline: z.string(),
    status: z.enum(["active", "shipped", "archived"]),
    stack: z.array(z.string()),
    repo: z.string().url(),
    demo: z.string().url().optional(),
    accent: z.tuple([z.number(), z.number(), z.number()]).optional(), // OKLCH [L C H]
    featured: z.boolean().default(false),
    order: z.number().default(0),
  }),
});

const devlogs = defineCollection({
  type: "content", // Markdown, generated by federate.ts
  schema: z.object({
    title: z.string(),
    date: z.coerce.date(),
    project: z.string(),
    tags: z.array(z.string()).default([]),
    draft: z.boolean().default(false),
  }),
});

// native, lives in-repo (not federated)
const cv = defineCollection({
  type: "content",
  schema: z.object({
    section: z.enum(["experience", "education", "skills", "certifications", "awards"]),
    title: z.string(),
    org: z.string().optional(),
    start: z.string().optional(),
    end: z.string().optional(),
    order: z.number().default(0),
  }),
});

const music = defineCollection({
  type: "data",
  schema: z.object({
    title: z.string(),
    source: z.enum(["soundcloud", "bandcamp"]),
    embedId: z.string(),      // just the ID/url fragment — no scraping
    year: z.number().optional(),
    accent: z.tuple([z.number(), z.number(), z.number()]).optional(), // OKLCH [L C H]
    // path under /public to a precomputed feature envelope (see
    // scripts/analyze-track.py) — when present, the track gets a
    // position-synced reactive Oscilloscope instead of a plain embed.
    envelope: z.string().optional(),
    // path under /public to a sinteza-viz schema-2 sidecar (see
    // sinteza-viz's scripts/analyze.ts, run against the original WAV
    // master) — a richer, separate file from `envelope` above. When
    // present, GlobalPlayer forwards it to the persistent background
    // visualizer via the player:transport bus's trackchange.track.envelope
    // (sinteza-viz's own field name for this — see its src/index.ts).
    sidecar: z.string().optional(),
  }),
});

export const collections = { projects, devlogs, cv, music };
